package:
  name: run_met
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.1') }}

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: 
    - $PYTHON setup.py install


requirements:
  build:
    - python
  run:
    - qt==4.8.7
    - python
    - ampsaws
    - obs2r
    - jpeg ==8d
    - yaml

about:
  home: https://github.com/MetServiceDev/run_met.git
